
'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import * as z from 'zod';
import { useTransition, useState } from 'react';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { Loader2 } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import Logo from '@/components/logo';
import { requestPasswordResetAction } from '../actions/auth';
import Link from 'next/link';

const formSchema = z.object({
  email: z.string().email({ message: 'Please enter a valid email address.' }),
});

type ForgotPasswordFormValues = z.infer<typeof formSchema>;

export default function ForgotPasswordPage() {
  const [isPending, startTransition] = useTransition();
  const { toast } = useToast();
  const [isSubmitted, setIsSubmitted] = useState(false);

  const form = useForm<ForgotPasswordFormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: { email: '' },
  });

  function onSubmit(data: ForgotPasswordFormValues) {
    startTransition(async () => {
      // This action now just simulates a request being sent.
      // The actual reset link is generated by the admin from the member list.
      const result = await requestPasswordResetAction(data.email);
      if (result.success) {
        setIsSubmitted(true);
        toast({
          title: 'Request Sent',
          description: "Your password reset request has been sent to the administrator.",
        });
      } else {
        toast({
          variant: 'destructive',
          title: 'Error',
          description: result.error || "An unknown error occurred.",
        });
      }
    });
  }

  return (
     <main className="flex min-h-screen flex-col items-center justify-center p-8 bg-background">
       <div className="w-full max-w-md">
        <Card>
          <CardHeader className="text-center">
            <div className="flex justify-center mb-4">
                <Logo />
            </div>
            <CardTitle>Forgot Your Password?</CardTitle>
            <CardDescription>
              {isSubmitted 
                ? "Your request has been sent to the administrator. Please contact them if you do not receive a reset link."
                : "Enter your email address to request a password reset from your administrator."
              }
            </CardDescription>
          </CardHeader>
          <CardContent>
            {!isSubmitted ? (
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                  <FormField
                    control={form.control}
                    name="email"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Email Address</FormLabel>
                        <FormControl>
                          <Input type="email" placeholder="e.g. alex.doe@example.com" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <Button type="submit" className="w-full" disabled={isPending}>
                    {isPending ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : "Request Password Reset"}
                  </Button>
                </form>
              </Form>
            ) : (
                <div className="text-center">
                    <p className="text-sm text-muted-foreground mb-4">You may close this window.</p>
                </div>
            )}
            <Button variant="link" className="w-full mt-4" asChild>
                <Link href="/">Back to Login</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
